# permissions for end users to view dossiers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dossier-viewer-role
rules:
- apiGroups:
  - dossier.di.unito.it
  resources:
  - dossiers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dossier.di.unito.it
  resources:
  - dossiers/status
  verbs:
  - get
