# permissions for end users to edit dossiers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dossier-editor-role
rules:
- apiGroups:
  - dossier.di.unito.it
  resources:
  - dossiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dossier.di.unito.it
  resources:
  - dossiers/status
  verbs:
  - get
