# permissions for end users to edit jupyterhubs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jupyterhub-editor-role
rules:
- apiGroups:
  - dossier.di.unito.it
  resources:
  - jupyterhubs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dossier.di.unito.it
  resources:
  - jupyterhubs/status
  verbs:
  - get
