# permissions for end users to edit postgresusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresuser-editor-role
rules:
- apiGroups:
  - dossier.di.unito.it
  resources:
  - postgresusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dossier.di.unito.it
  resources:
  - postgresusers/status
  verbs:
  - get
