# permissions for end users to view postgresusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresuser-viewer-role
rules:
- apiGroups:
  - streamflow.edu.unito.it
  resources:
  - postgresusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - streamflow.edu.unito.it
  resources:
  - postgresusers/status
  verbs:
  - get
