---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - dossier.di.unito.it
  resources:
  - dossiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dossier.di.unito.it
  resources:
  - dossiers/finalizers
  verbs:
  - update
- apiGroups:
  - dossier.di.unito.it
  resources:
  - dossiers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dossier.di.unito.it
  resources:
  - postgresusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dossier.di.unito.it
  resources:
  - postgresusers/finalizers
  verbs:
  - update
- apiGroups:
  - dossier.di.unito.it
  resources:
  - postgresusers/status
  verbs:
  - get
  - patch
  - update
