---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - streamflow.edu.unito.it
  resources:
  - dossiers
  - jupyterhubs
  - postgresqls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - streamflow.edu.unito.it
  resources:
  - dossiers/finalizers
  verbs:
  - update
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - get
    - list