# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/dossier.di.unito.it_jupyterhubs.yaml
- bases/dossier.di.unito.it_dossiers.yaml
- bases/dossier.di.unito.it_postgresqls.yaml
- bases/dossier.di.unito.it_postgresusers.yaml
#+kubebuilder:scaffold:crdkustomizeresource
